---
title: Painless Code
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Easy to understand coding tutorials.
baseurl: ''
url: http://painlesscode.com
twitter_username: arielcr
github_username: arielcr
permalink: "/:categories/:title/"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
disqus:
    shortname: painless-code
google_analytics: UA-3469370-9