---
title: Painless Code
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: bassplayer85@gmail.com
description: Easy to understand coding tutorials.
baseurl: ''
url: http://painlesscode.com
twitter_username: arielcr
github_username: arielcr
permalink: "/:categories/:title/"
markdown: kramdown
theme: jekyll-theme-time-machine
plugins:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
